language: node_js

node_js:
  - 'lts/*'

before_install:
  - export PATH=./node_modules/.bin/:$PATH
  - npm install -g npm
  - npm update

install:
  - npm install
  - npm run test

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - m.vergoz@vergoz.ch
    on_success: never
    on_failure: always

env:
  - LANG="en_US.UTF-8"
os:
  - linux

dist: bionic
